#!/bin/sh /etc/rc.common
START=99

# 运行自动更新的函数
run_autoupdate() {
    # 检查自动更新脚本和配置文件是否存在
    if [ -f "/usr/bin/AutoUpdate" ] && [ -f "/etc/openwrt_update" ]; then
        local enable
        local use_no_config_update
        # 从配置中获取启用状态和勾选框状态
        config_get_bool enable "$1" enable
        config_get use_no_config_update "$1" use_no_config_update

        if [ "$enable" = "1" ]; then
            local minute
            local hour
            local week
            # 从配置中获取时间相关设置
            config_get week "$1" week
            config_get minute "$1" minute
            config_get hour "$1" hour
            # 如果 week 为 7，转换为 * 表示每周
            [ "$week" = "7" ] && week="*"
            # 从 crontab 中删除与 AutoUpdate 相关的任务
            sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1

            # 根据勾选框状态选择命令
            local update_command
            if [ "$use_no_config_update" = "1" ]; then
                update_command="AutoUpdate -k"
            else
                update_command="AutoUpdate -u"
            fi

            # 添加新的自动更新任务到 crontab
            echo "$minute $hour * * $week $update_command" >> /etc/crontabs/root
            # 重启 cron 服务使新任务生效
            /etc/init.d/cron restart
        fi

        local cus_url
        # 获取自定义的 GitHub 网址
        cus_url=$(uci get autoupdate.@login[0].github)
        if echo "${cus_url}" | grep -E "https://github.com/.*/" >/dev/null 2>&1; then
            local custom_github_url
            # 从配置文件中获取已有的自定义 GitHub 网址
            custom_github_url=$(awk -F'=' '/GITHUB_LINK=/ {gsub(/"/, "", $2); print $2}' /etc/openwrt_update)
            local LAN_IP
            # 获取局域网 IP 地址
            LAN_IP=$(uci get network.lan.ipaddr)
        fi

        if [ -n "${custom_github_url}" ] && [ "${cus_url}" != "${custom_github_url}" ]; then
            # 更新配置文件中的 GitHub 网址
            sed -i "s?${custom_github_url}?${cus_url}?g" /etc/openwrt_update
            uci commit autoupdate
            # 触发 LuCI 页面更新
            curl "http://$LAN_IP/cgi-bin/luci/admin/system/autoupdate" >/dev/null 2>&1
        fi
    else
        echo "自动更新脚本或配置文件不存在，无法运行自动更新。"
    fi
}

# 启动函数
start() {
    config_load autoupdate
    config_foreach run_autoupdate login
}

# 停止函数
stop() {
    # 从 crontab 中删除与 AutoUpdate 相关的任务
    sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
    # 重启 cron 服务
    /etc/init.d/cron restart
}

# 重启函数
restart() {
    stop
    start
}
