#!/bin/sh /etc/rc.common
START=99

run_autoupdate()
{
	if [ -f "/usr/bin/AutoUpdate" ] && [ -f "/bin/openwrt_info" ]; then
		local enable
		config_get_bool enable $1 enable
		if [ $enable == "1" ]; then
			local minute
			local hour
			config_get week $1 week
			config_get minute $1 minute
			config_get hour $1 hour
			[ "$week" == 7 ] && week="*"
			sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
			echo "$minute $hour * * $week AutoUpdate -u" >> /etc/crontabs/root
			/etc/init.d/cron restart
		else
			stop	
		fi
		cus_url="$(uci get autoupdate.@login[0].github)"
		if [[ "$(echo ${cus_url} |grep -c 'https://github.com/.*/.*')" == '1' ]]; then
                	ApAuthor="${cus_url%.git*}"
                	custom_github_url="${ApAuthor##*com/}"
			current_github_url="$(grep Warehouse= /bin/openwrt_info | cut -d "=" -f2)"
		fi
		if [[ -n "${custom_github_url}" ]] && [[ "${custom_github_url}" != "${current_github_url}" ]]; then
			sed -i "s?${current_github_url}?${custom_github_url}?g" /bin/openwrt_info
        		Input_Other="$(grep Github= /bin/openwrt_info | cut -d "=" -f2)"
			uci set autoupdate.@login[0].github=${Input_Other}
 			uci commit autoupdate
		fi
	fi
}


start()
{
	config_load autoupdate
	config_foreach run_autoupdate login
}

stop()
{
	sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
	/etc/init.d/cron restart
}

restart()
{
	stop
	start
}
