#
#
# 因为SSH连接配置固件直接编译，会给github停止编译的
#
# 所以本文件是专门用来连接SSH配置.config文件专用
#
# 跟启动编译是一样的，已经默就打开SSH，选择好生成什么源码的.config文件，然后启动，等待进入SSH连接，然后配置文件
#
# 配置完成后会自动上传一份.config文件，下载下来，覆盖到对应的源码上的.config就可以编译了
#
# 如果配置了REPO_TOKEN密匙的话，则会把.config文件自动覆盖到对应源码文件夹的.config中，免除手动覆盖
#
# REPO_TOKEN密匙制作教程：https://git.io/jm.md
#
#

name: 配置.config文件
on:
  workflow_dispatch:
    inputs:
      config:
        description: 'true-actions改成true,再按Run workflow启动,若配置文件有更新随即自动启动对应源码编译固件'
        required: false
        default: 'true-actions'

env: 
 REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
 TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 准备结束
      uses: actions/checkout@v2
        
    - name: 部署制作.config文件环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update > /dev/null 2>&1
        sudo -E apt-get -qq install -y subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip git-core wget curl grep > /dev/null 2>&1
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: 更新build-openwrt.yml文件，用于修改.config后启动"${{matrix.target}}"编译（需要密匙和true-actions改成true）
      run: |
        cd $GITHUB_WORKSPACE
        git clone -b main https://github.com/281677160/luci-app-autoupdate.git main
        cd main
        chmod -R 777 $GITHUB_WORKSPACE/main
        git add .
        git commit -m "Update autoupdate" |tee build.log
        if [[ `grep -c "Your branch is up to date with" build.log` -eq '1' ]]; then
          echo "配置文件无更新,所以无需要覆盖!"
        else
          rm -fr build.log
          echo "正在更新build-openwrt.yml文件!"
          git push --quiet "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
          echo "更新完毕!"
        fi
